services:
  tor-clearnet:
    image: ghcr.io/e3ndr/tor-clearnet:latest
    restart: unless-stopped
    environment:
      SERVICE_NAME: "My TorClearnet Proxy"
      BLOCKLISTS: "ahmia"
      SOCKS_PROXY: "tor-simple"
      SOCKS_PORT: "9050"
    depends_on:
      - tor-simple
    ports:
      - 9000:80 # Change 9000 to your liking.

  tor-simple:
    image: osminogin/tor-simple
    restart: unless-stopped
